spring.datasource.url=jdbc:postgresql://localhost:5432/hustle
spring.datasource.username=postgres
spring.datasource.password=abhishek6280

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=5000

jwt.secret=48659752984621578965231456789456
jwt.expiration=86400000